name: jooblie_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^8.0.2
  animate_do: ^3.3.4
  icons_plus: ^5.0.0
  supercharged: ^2.1.1
  app_links: ^6.3.0
  share_plus: ^10.1.4
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  another_flushbar: ^1.12.32
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.4
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - .env